name: Publish Node.js Package

on:
  release:
    types: [published]
  workflow_call:
    inputs:
      node_version:
        description: 'Node version to use'
        required: true
        type: string
        default: '20'
      registry_url:
        description: 'NPM registry URL'
        required: true
        type: string
        default: 'https://registry.npmjs.org/'
      scope:
        description: 'Scope for npm package'
        required: false
        type: string
        default: 'openimis'
      access:
        description: 'Access level for npm package'
        required: false
        type: string
        default: 'public'
      tag:
        description: 'Dist-tag for the npm publish (v1.2 ...)'
        required: true
        type: string

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0  # Needed for git fetch --tags

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: ${{ inputs.node_version }}
          registry-url: ${{ inputs.registry_url }}
          scope: ${{ inputs.scope }}

      - name: Update version with TAG
        run: |
          TAG_NAME="${{ inputs.tag }}"
          if [ -z "$TAG_NAME" ]; then
            if [ "${{ github.event_name }}" == "release" ]; then
              TAG_NAME="${{ github.event.release.tag_name }}"
            else
              git fetch --tags
              TAG_NAME=$(git tag --sort=-version:refname | head -n 1)
            fi
          fi
          echo "tag to use $TAG_NAME"
          jq --arg a "$TAG_NAME" '.version = $a' package.json > temp.json && mv temp.json package.json

      - name: Install dependencies
        run: yarn install

      - name: Publish package
        run: |
          if [ -n "${{ inputs.tag }}" ]; then
            yarn publish --tag ${{ inputs.tag }} --access ${{ inputs.access }} --no-git-tag-version
          else
            yarn publish --access ${{ inputs.access }} --no-git-tag-version
          fi
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
