name: Publish Node.js Package

on:
  release:
    types: [published]
  workflow_call:
    inputs:
      node_version:
        description: 'Node version to use'
        required: true
        type: string
        default: '20'
      registry_url:
        description: 'NPM registry URL'
        required: true
        type: string
        default: 'https://registry.npmjs.org/'
      scope:
        description: 'Scope for npm package'
        required: false
        type: string
        default: 'openimis'
      access:
        description: 'Access level for npm package'
        required: false
        type: string
        default: 'public'
      tag:
        description: 'Dist-tag for the npm publish (v1.2 ...)'
        required: true
        type: string

jobs:
  # -------------------------------------------------
  # Publish to npmjs.com
  # -------------------------------------------------
  npmjs:
    uses: openimis/openimis-fe_js/.github/workflows/module-npmpublish.yml@develop
    with:
      registry_url: ${{ inputs.registry_url || 'https://registry.npmjs.org/' }}
      node_version: ${{ inputs.node_version || '20' }}
      scope:        ${{ inputs.scope        || 'openimis' }}
      access:       ${{ inputs.access       || 'public' }}
      tag:          ${{ inputs.tag          || 'latest' }}
    secrets:
      NPM_TOKEN: ${{ secrets.NPM_TOKEN }}

  # -------------------------------------------------
  # Publish to GitHub Packages (GPR)
  # -------------------------------------------------
  gpr:
    needs: npmjs                     # optional – wait for npmjs to finish
    uses: openimis/openimis-fe_js/.github/workflows/module-npmpublish.yml@develop
    with:
      registry_url: 'https://npm.pkg.github.com/'
      node_version: ${{ inputs.node_version || '20' }}
      scope:        ${{ inputs.scope        || 'openimis' }}
      access:       ${{ inputs.access       || 'public' }}
      tag:          ${{ inputs.tag          || 'latest' }}
    secrets:
      NPM_TOKEN: ${{ secrets.GITHUB_TOKEN }}
